version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: "fix(deps)"
    groups:
      go:
        patterns: ["*"]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: "ci"
    groups:
      actions:
        patterns: ["*"]

  - package-ecosystem: docker
    directories: [/, /test/e2e]
    schedule:
      interval: weekly
    commit-message:
      prefix: "build"
